version: '2'

volumes:
  database: {}
  production: {}

services:
  db:
    image: mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: app
    ports:
      - '3306'
    volumes:
      - .:/app/mysql

  app:
    image: app
    build: .
    ports:
      - '3000:3000'
    links:
      - db
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:root_pass@db/app
    volumes:
      - .:/app
